### ISSUE TITLE
tap broken

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#254]
```
Hi ,

i try to use  def tap(opts) its not allowing me to pass parameters if i pass any parameters it says 1 or zero aruments exception

here are the my implmentaions
1.i tired tap(:x => 0.5,:y => 0.5,:fingers => 1) does't worked
2.   @op = {
    opts: {
        'x' => 0.5,
        'y' => 0.5,
        'fingers' => 1
    }}

    tap(@op) - does't worked

correct me if i am wrong in implementation
```

reported by @prathimak

**Comment by bgrimes78** [comment]
This worked for me:

Appium::TouchAction.new.tap(:x => 50, :y => 70).release.perform

**Comment by bgrimes78** [comment]
So one point to make, I can use swipe without referencing the module and class, but tap I need to.  Why is that?

swipe(:start_x => a, :start_y => b, :end_x => c, :end_y => d, :duration => e).perform

Appium::TouchAction.new.tap(:x => 50, :y => 70).release.perform

**Comment by aleks2a** [comment]
it is still broken..

**Comment by sofaking** [comment]
@aleks2a could you provide an example what exactly does not work? What appium version? Android?
For example code like this ```Appium::TouchAction.new.tap(x: 60, y: 1200).perform``` works like a charm for me.

**Comment by KazuCocoa** [comment]
according to the comment, https://github.com/appium/ruby_lib/issues/254#issuecomment-221553085, and source code `Appium::TouchAction.new.tap(x: 60, y: 1200).perform` seems work.
If someone can't `tap` with latest appium server and ruby_lib, let open an issue.

**Comment by nairouz12** [comment]
I have the same issue with appium 1.6.3
I have a XCUIElementTypeAlert displayed on my screen
these are the coordinates of my XCUIElementTypeAlert:
x=52, y=263, h=141, w=271
and this is the size of my screen where XCUIElementTypeAlert is displayed: height = 667, width = 375
I would like to tap outside XCUIElementTypeAlert:
`> Appium::TouchAction.new.tap(:x => 0, :y => window_size.width*0.5).release.perform
Selenium::WebDriver::Error::UnknownError: Support for this gesture is not yet implemented. Please contact an Appium dev
from /Users/admin/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'`

and when I try without release, it does not give any error but it tap the first button of the element instead of tapping outside:
`Appium::TouchAction.new.tap(:x => 0, :y => window_size.width*0.5).perform
#<Appium::TouchAction:0x007fe958d77fa0 @actions=[{:action=>:tap, :options=>{:x=>0, :y=>187.5, :count=>1}}]>`

**Comment by KazuCocoa** [comment]
I created ^ comment as new issue

https://github.com/appium/ruby_lib/issues/453
