### ISSUE TITLE
underlying webdriver instance does not support javascript

### ISSUE THREAD

**Issue by danqa** [appium/ruby_lib#390]
Getting the following error when running appium script:

```
Users/matt/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:616:in `assert_javascript_enabled’: underlying webdriver instance does not support javascript (Selenium::WebDriver::Error::UnsupportedOperationError)

from /Users/matt/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:351:in `executeScript’

from /Users/matt/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:220:in `execute_script’

from /Users/matt/.rvm/gems/ruby-2.3.0/gems/appium_lib-8.0.2/lib/appium_lib/driver.rb:572:in `execute_script’

from appium-ios-me.rb:26:in `<main>’
```

This occurs when trying to do something like this:
` $selenium_driver.execute_script('return document.querySelector(".info__nav__desc")') != [] `

I spoke with Saucelabs and they tried in Java and it worked fine but when using the appium_lib ruby bindings I get this error. So they pointed me here. 

Also note that Sauce stated:
```
I also tested with iOS 9.3, which uses iOSDriver rather than XCUITest and there was no problem there, so the issue does appear to be with XCUITest in particular.
```

Hoping you can help.

Sincerely,
Daniel

**Comment by KazuCocoa** [comment]
In `ruby_lib`, `execute_script` call selenium-webdriver directly.

- [here](https://github.com/appium/ruby_lib/blob/09654ab9dbc69a31eff7e7bd426db985da09e3b8/lib/appium_lib/driver.rb#L583)

```ruby
    def execute_script(script, *args)
      @driver.execute_script script, *args
    end
```

selenium-webdriver's `execute_script` called the following methods.

- [here](https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/rb/lib/selenium/webdriver/common/driver.rb#L219) in selenium-webdriver

```ruby
      def execute_script(script, *args)
        bridge.executeScript(script, *args)
      end
```

In `executeScript`, `assert_javascript_enabled` is called. ([here](https://github.com/SeleniumHQ/selenium/blob/650a1ab4fe3f0363cde72d8e0202e61e3f713acd/rb/lib/selenium/webdriver/remote/bridge.rb#L618) is code)

```ruby
        def assert_javascript_enabled
          return if capabilities.javascript_enabled?
          raise Error::UnsupportedOperationError, "underlying webdriver instance does not support javascript"
        end
```

Your raised error might come from this raise error.
You can check `capabilities.javascript_enabled?` like the following.

```ruby
rquire 'pry'
a = start_driver(caps)
binding.pry
```

Run tests and check the driver with `pry` debugger.

```
[1] pry(main)> a.capabilities
=> #<Selenium::WebDriver::Remote::Capabilities:0x007fdae3380868
@capabilities=
 {:browser_name=>"",
  :version=>nil,
  :platform=>:mac,
  :javascript_enabled=>true,
  :css_selectors_enabled=>nil,
  :takes_screenshot=>true,
  :native_events=>nil,
  :rotatable=>nil,
  :firefox_profile=>nil,
  :proxy=>nil,
  "webStorageEnabled"=>false,
  "locationContextEnabled"=>false,
  "databaseEnabled"=>false,
  "networkConnectionEnabled"=>false,
  "platformName"=>"ios",
  "platformVersion"=>"9.3",
  "deviceName"=>"iPhone Simulator",
  "automationName"=>"XCUITest",
  "app"=>
   "/Users/kazuaki/Documents/github/ruby_lib/ios_tests/UICatalog.app"}>
[3] pry(main)> a.capabilities.javascript_enabled?
=> true
```

How about the result of `a.capabilities.javascript_enabled?` in your case?
If `false`, `javascript_enabled` was failed to set `true`.

The above result is just test suite in this project's `ios_test` [here](https://github.com/appium/ruby_lib/tree/master/ios_tests)

**Comment by danqa** [comment]
@KazuCocoa 

Seems to be set
```
=> #<Selenium::WebDriver::Remote::Capabilities:0x007fdc6ad5cfc0
 @capabilities=
  {:browser_name=>"",
   :version=>nil,
   :platform=>:mac,
   :javascript_enabled=>true,
   :css_selectors_enabled=>nil,
   :takes_screenshot=>true,
   :native_events=>nil,
   :rotatable=>nil,
   :firefox_profile=>nil,
   :proxy=>nil,
   "webStorageEnabled"=>false,
   "locationContextEnabled"=>false,
   "databaseEnabled"=>false,
   "networkConnectionEnabled"=>false,
   "platformName"=>"iOS",
   "platformVersion"=>"10.0",
[2] pry(#<RSpec::ExampleGroups::MyProfile>)> $selenium_driver.capabilities.javascript_enabled?
=> true
```

**Comment by danqa** [comment]
Why is that check even needed or maybe modify the code to be default true and user can change to false? I am not sure why we would not want to have JS on by default. That being set. I seem to be setting it but selenium thinks I am not and I am not sure why.

**Comment by jlipps** [comment]
@danqa yeah it's a thing some clients do to try and protect their users from using methods which will fail. It expects to see `javascript_enabled` in the capabilities response from the server in order to allow library users to use the execute script methods.

But what's odd is it seems everything is in order here....

Your most recent post was from the Sauce Labs test run?

**Comment by danqa** [comment]
@jlipps yes

**Comment by jlipps** [comment]
I'm really not sure then. Are you using the same version of ruby_lib as @KazuCocoa?

**Comment by KazuCocoa** [comment]
I used current master branch. BTW, 8.0.2, current published gem version,  works as well as master branch in this case, I think. But I tried only in my local environment, not on the cloud.

I read https://github.com/appium/appium/issues/5623#issuecomment-259710842 .

> its happing in their cloud but not for me locally (which is very odd). 

🤔

I'll check code again later.

**Comment by danqa** [comment]
@KazuCocoa @jlipps yes 

`Using appium_lib 8.0.2`

so same version.

**Comment by JaniJegoroff** [comment]
@danqa I can't reproduce this issue with XCUITest driver.
- iOS 10.1
- ruby_lib 8.0.2
- latest Appium v1.6.1-beta

I created simple example project, could you try it out?

https://github.com/JaniJegoroff/appium-test-browser
http://www.screencast.com/t/CO6sX95QD

**Comment by danqa** [comment]
@JaniJegoroff I am on Appium 1.6.0 which is the latest stable and I believe Sauce is only on 1.6.0. Can you try with that?

Thanks for the help.

**Comment by JaniJegoroff** [comment]
No problems with stable Appium 1.6.0 either.

```
[Appium] Welcome to Appium v1.6.0 (REV b77a695b7a0c9094d49993d26921a47da919364d)

[1] pry(main)> execute_script('return document.title')
"Appium/welcome"

[HTTP] --> POST /wd/hub/session/9f13c017-b27d-40b7-8da9-226f3cdbdcf6/execute {"script":"return document.title","args":[]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["return document.title",[]...
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":"Appium...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'execute_script' execution: "Appium/welcome"
[MJSONWP] Responding to client with driver.execute() result: "Appium/welcome"
[HTTP] <-- POST /wd/hub/session/9f13c017-b27d-40b7-8da9-226f3cdbdcf6/execute 200 508 ms - 88
```

**Comment by danqa** [comment]
@JaniJegoroff yea works for me locally as well: 

```
Local: ~/appium-test-browser (master) $ vi appium.txt
Local: ~/appium-test-browser (master) $ bundle exec arc
[1] pry(main)> execute_script('return document.title')
"Appium/welcome"
```

I have a ticket open with Sauce and they can repro it when they do it locally. I don't know what could be different with them (espically since he is running locally as well) but its seems to be something specific to Sauce (even though they think its on the appium_lib side). 

Kinda stumped.

**Comment by KazuCocoa** [comment]
I tried to reproduce the raised error. The only case I could raise: 

```ruby
Selenium::WebDriver::Error::UnsupportedOperationError: underlying webdriver ...
```

is set `> driver.capabilities.javascript_enabled = false` directly... But `appium_lib` don't have such code.

The only case `javascript_enabled` is `false` by default is selected `htmlunit`'s capability, [here](https://github.com/SeleniumHQ/selenium/blob/7e8f5f1e8ee8965e0d54a51767de1d766570de1a/rb/lib/selenium/webdriver/remote/capabilities.rb#L89). But `appium_lib` don't select the capability. `appium_lib` uses `FireFox`'s default capability due to the library uses `Remote` capability. ([here](https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/rb/lib/selenium/webdriver/remote/bridge.rb#L66) is initializer in selenium-webdriver.)

>  but its seems to be something specific to Sauce (even though they think its on the appium_lib side).

hmm...
We need to try on Sauce, not our local environments... Currently, I also couldn't reproduce issue in my local ...)

**Comment by danqa** [comment]
@KazuCocoa have you has a chance to try on Sauce?

**Comment by KazuCocoa** [comment]
I have tried on Sauce with my free trial.
I summarized my investigation in the following gist.

https://gist.github.com/KazuCocoa/acf365a3a6f5fd71708adb1ada776348

Then, I could see the following JS error only on Sauce case, even the test can run without `underlying webdriver instance does not support javascript ` error. 

```
/Users/my/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:616:in `assert_javascript_enabled': underlying webdriver instance does not support javascript (Selenium::WebDriver::Error::UnsupportedOperationError)
    from /Users/my/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:351:in `executeScript'
    from /Users/my/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:220:in `execute_script'
    from /Users/my/Documents/github/ruby_lib/lib/appium_lib/driver.rb:586:in `execute_script'
    from main.rb:24:in `<main>'
```

**Comment by KazuCocoa** [comment]
@jlipps I have checked this error and this may happen only on Sauce.
Could you check the result ?

**Comment by danqa** [comment]
Hi @jlipps Any update on this?

**Comment by nimbuscrenel** [comment]
I'm also seeing this same issue and have a ticket with Sauce too. As far as I can tell this only occurs with iOS 10, all other versions work fine.

**Comment by jlipps** [comment]
@danqa could you retry again with the `javascript_enabled` capability set to `true` instead of `"true"`?

**Comment by danqa** [comment]
@jlipps did not work. Here are my caps:

```
caps = {
      'deviceOrientation' => 'portrait',
      'platformVersion' => '10.0',
      'browserName' => '',
      'appiumVersion' => '1.6.0',
      'platformName' => 'iOS',
      'deviceName' => 'iPhone Simulator',
      'sendKeyStrategy' => 'setValue',
      'autoWebview' => 'true',
      'automationName' => 'XCUITest',
      'javascript_enabled' => true,
      'fullReset' => 'true'
    }
```

Still get `underlying webdriver instance does not support javascript`

**Comment by jlipps** [comment]
@danqa can you send me the test url for that run

**Comment by danqa** [comment]
@jlipps 

https://saucelabs.com/jobs/c28b1554bd614017a53e0b576491b832 

Let me know if you need anything else.

Thank you.

**Comment by danqa** [comment]
Hi @jlipps Hope your holidays were good. Wanted to see if you were able to get anything useful out of those Sauce logs.

**Comment by danqa** [comment]
Hey guys. Is there any update here?

**Comment by jlipps** [comment]
@danqa digging into this a bit more, the problem seems to be with WebDriverAgent. When you `GET /session/:id` it returns a JSON object like this:

> {"status": 0, "sessionId": "1ddfd26aeb1149528c20f594204995a4", "value": {"sessionId": "200CB1B5-B743-4E35-A4D0-7880A392BC84", "webdriver.remote.sessionid": "1ddfd26aeb1149528c20f594204995a4", "hasMetadata": true, "capabilities": {"device": "iphone", "CFBundleIdentifier": "io.appium.TestApp", "browserName": "TestApp", "sdkVersion": "10.0"}}

Note that the "capabilities" object is definitely not what we want. It has some odd things in it that we don't care about, and also _doesn't_ reply with `javascript_enabled` set to `true`.

I have a fix in mind, but I'm confused, because this _should_ reproduce locally, not just on Sauce. Can you give it another go with Appium 1.6.2, and iOS 10, and ensure you use the XCUITest driver? I want to make sure it fails for you as expected. Once you confirm that I'll be able to get on a fix which will be available in the next version of Appium.

(I also proved that, on Sauce, when _not_ using the XCUITest driver, the capabilities response correctly includes `javascript_enabled`.)

In general though, I'm not a fan of clients caring too much what gets sent back in the session capabilities response. At the end of the day, there's nothing stopping you from running your execute_script command except for the ruby client. It's not a bug in the ruby client per se, but IMO it cares too much about what the server reports in an attempt to keep the user from running into an error. Is there any way to disable this behavior in the ruby client, for the time being?

**Comment by danqa** [comment]
@jlipps I **cannot** reproduce it locally

Here are my caps:
```
caps = {
      'platformName' => 'iOS',
      'platformVersion' => '**10.1**',
      'app' => 'my.app',
      'deviceName' => 'iPhone 6',
      'sendKeyStrategy' => 'setValue',
      'autoWebview' => 'true',
      'fullReset' => 'true',
      'automationName' => '**XCUITest**',
      **'javascript_enabled' => true**,
      'alert_accept' => 'true'
    }
```

I am running Appium 1.6.2
```
[Appium] Welcome to Appium v1.6.2 (REV 5b4713a677bb0f195485a91b356ade895e8db1b7)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

And I have code in my scripts like this: 
```
$selenium_driver.execute_script("document.querySelector('#{CSS_SELECTORS[action]}').value = '#{argument}'")
```

Runs just fine on my machine. 😕

**Comment by jlipps** [comment]
@danqa can you attach the logs for that run?

**Comment by danqa** [comment]
@jlipps https://gist.github.com/danqa/31ed066545cfac1025fb8a785d973f99

**Comment by jlipps** [comment]
Aha. I've figured out what the problem is. On Sauce, new sessions are responded to with a 303 status code and a link to `GET /sessions/:sessionid`. In this case, the ruby client calls that URL and retrieves the capabilities from it, which it uses to restrict its behavior. Whenever you call that URL against Appium, whether on Sauce or locally, it proxies the request to WDA, which responds with the invalid desired capabilities. That's the problem.

Why does it work locally then? Locally, new sessions are responded to with a 200 status code and the desired capabilities options directly. In this case, the ruby client does _not_ make the additional call, which is therefore _not_ proxied to WDA, and the invalid capabilities are never sent back to the ruby client. Instead, it uses what it got as a result of creating the session, which Appium makes up with no reference to WDA.

So the solution I have in mind will still work.

**Comment by jlipps** [comment]
Track https://github.com/appium/appium/issues/7480 for resolution

**Comment by KazuCocoa** [comment]
Already resolved? @danqa

**Comment by KazuCocoa** [comment]
please reopen if you need
