### ISSUE TITLE
when I set up test environment,I want to run the android test cases ,something wrong has appeared all the time 

### ISSUE THREAD

**Issue by tangtingting** [appium/ruby_lib#452]
**I exec "rake install"**
rake install
fatal: Not a git repository (or **any** of the parent directories): .git
bundle install
fatal: Not a git repository (or any of the parent directories): .git
Resolving dependencies...
Using rake 12.0.0 
............

**Then I exec "git init" in the current directory**
$ sudo git init
Reinitialized existing Git repository in /usr/share/rvm/gems/ruby-2.2.6/gems/appium_lib-9.1.2/android_tests/.git/
$ ls -a
.   api.apk     flaky.txt  Gemfile.lock  lib              Rakefile
..  appium.txt  Gemfile    .git          LICENSE-2.0.txt  readme.md

**but when I ran rake command ,the same problem occured again.**

**git function seems right. and I haven't discovered other questions until now .but I don't know why this problem always exist when I exec rake command**
 git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   readme.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Gemfile

**Comment by KazuCocoa** [comment]
@tangtingting 

It happens when `git ls-files` is called in: https://github.com/appium/ruby_lib/blob/master/appium_lib.gemspec#L32 , I think.

`ruby_lib/android_test/Gemfile` and `ruby_lib/ios_test/Gemfile` always read `ruby_lib/appium_lib.gemspec`. So, you should `git init` in `ruby_lib/` if you would like to prevent the error.

Did you clone this repository into your machine with `git clone`? This error may be occurred with zip download since zip doesn't have `.git`.

I think the following steps may work well.
```
$ git clone git@github.com:appium/ruby_lib.git
$ cd ruby_lib/android-test
$ rake install
```

**Comment by tangtingting** [comment]
Thanks very much,My issue has been solved with exec "git init" in  appium_lib/  directory.

**Comment by KazuCocoa** [comment]
👍
