### ISSUE TITLE
Pulling session_capabilities of a driver does not match documentation

### ISSUE THREAD

**Issue by brandondjango** [appium/ruby_lib#833]
## This is a
* [ ] Bug report
* [ ] Question
* [ x ] Feature Request

## Summary
Appium documentation here: http://appium.io/docs/en/commands/session/get/index.html

This method doesn't exist. I think the closest thing to getting a drivers capabilities is using this method: driver_attributes.

Then you would just use a hash key to get to the caps.

What I'm looking for is: 

def session_capabilities
   @core.caps
end

I have added the method locally and it appears to be working as I would expect.

I couldn't run the flake tests so I didn't want to put in a PR.

Thanks.

## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:

## Actual behavior and steps to reproduce
Call @driver.session_capabilities and the method does not exist

## Expected behavior
Call @driver.session_capabilities and get back the capabilities of the session

**Comment by KazuCocoa** [comment]
that is https://github.com/appium/ruby_lib_core/blob/f8af2e3e8dbff2e6616c554db6394b42c588ddeb/lib/appium_lib_core/common/base/driver.rb#L727

or `driver.session_capabilities` (with global driver in ruby_lib) case.

I'll update the doc to follow global driver in ruby_lib and instance driver based in ruby_lib_core.
(since the ruby_lib is ordinally `$driver` based one, i guess)

**Comment by brandondjango** [comment]
Ah gotcha. Sorry, this is essentially the same issue as before.  Just working my way through.

Thanks!
