### ISSUE TITLE
Scroll does not work

### ISSUE THREAD

**Issue by lflucasferreira** [appium/ruby_lib#867]
## The problem

Guys, I am wasting two days just trying to find how to scroll to a specific part of the screen. I thought this framework would save me time, but it is not.

Could anyone tell how to perform a scrolling action?

## Environment

* Appium version (or git revision) that exhibits the issue: **1.15.1**
* Desktop OS/version used to run Appium: **Windows 10 Professional**
* Node.js version (unless using Appium.app|exe): **v10.16.3**
* Npm or Yarn package manager: **6.9.0**
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

I tried this one:
```
@driver.touch_action.down(element).move_to(10, 100).up(50, 50).perform
```
But **touch_action** is not recognized.

Then I tried this one:
```
execute_script 'mobile: scroll', direction: 'down'
```
But it says that the command scroll is an unknown mobile command. 

I really do not know what to do. Appium's documentation does not help at all.

## Link to Appium logs

```
[13] pry(main)> driver.execute_script('mobile: scroll', {'direction': 'down'})
Selenium::WebDriver::Error::UnknownCommandError: Unknown mobile command "scroll". Only shell,scrollBackTo,viewportScreenshot,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,changePermissions,getPermissions,performEditorAction commands are supported.
from UnknownCommandError: Unknown mobile command "scroll". Only shell,scrollBackTo,viewportScreenshot,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,changePermissions,getPermissions,performEditorAction commands are supported.
```

**Comment by lflucasferreira** [comment]
Sorry, but I am new to all of this. I tried to perform the action but it returned **nil**.
I really don't understand why Appium does not have a simple method to scroll up and down to a specific point/element.

What worked for me but I didn't accept the way is this one:

```
Appium::TouchAction.new.swipe({ start_y: 700, duration: 400 }).perform
```

This is not good for a test scenario because the developer can one day include/remove an element and break the structure.

If you have a good example, just for scrolling to a specific element (vertically) I would be very thankful.

**Comment by JaniJegoroff** [comment]
@lflucasferreira If such functionality is missing feel free to contribute to the project :)

**Comment by KazuCocoa** [comment]
> it returned nil

It is common for some commands which have no particular return values.

> I really don't understand why Appium does not have a simple method to scroll up and down to a specific point/element.

Do you mean like https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/TouchAction ?
https://www.rubydoc.info/github/appium/ruby_lib/Appium/TouchAction's swipe is a wrapper method for the press/wait/move_to. ruby_lib wraps ruby_lib_core. You can call the actions via TouchAction.

As W3C spec, http://appium.io/docs/en/commands/interactions/actions/ will be such actions. The TouchActions is not W3C spec one.

**Comment by RussellJoshuaA** [comment]
@KazuCocoa 

> Do you mean like https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/TouchAction ?
https://www.rubydoc.info/github/appium/ruby_lib/Appium/TouchAction's swipe is a wrapper method for the press/wait/move_to. ruby_lib wraps ruby_lib_core. You can call the actions via TouchAction.

I'm struggling hard with this. It seems to me that this is a catch-22: To move_to element, I must find_element (because I have to pass it in as a param); to find_element, I must move_to element (because find_element fails when the element is off screen).

Am I missing something?

**Comment by lflucasferreira** [comment]
I simply gave up on this.

**Comment by KazuCocoa** [comment]
Below test cases could help to do scroll based on coordinates and elements. They are via ruby_lib_core, but they work via ruby_lib as well. See http://appium.io/docs/en/commands/interactions/actions/

https://github.com/appium/ruby_lib_core/blob/76190523c95e3f6a1ab9a9af48d60605d2f87266/test/functional/common_w3c_actions.rb#L16-L29
https://github.com/appium/ruby_lib_core/blob/master/test/functional/android/webdriver/w3c_actions_test.rb
https://github.com/appium/ruby_lib_core/blob/master/test/functional/ios/webdriver/w3c_actions_test.rb

TouchAction is not maintained so well because it is not W3C spec. Appium is going to focus on W3C spec and a couple of intentional commands.
